"""Generate human-readable reports from host-side rollout evidence; no model calls."""
import argparse
from datetime import datetime
import hashlib
import json
import os
from pathlib import Path
from zoneinfo import ZoneInfo

HERE = Path(__file__).resolve().parents[1]
MARKER = "<!-- Generated by harbor_local.runtime.reporting; edit source notes, not this file. -->"


def read_json(path):
    return json.loads(path.read_text()) if path.is_file() else {}


def link(label, target, directory):
    return f"[{label}](<{os.path.relpath(target, directory)}>)"


def local_time(value):
    if not value:
        return "未记录"
    return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(ZoneInfo("Asia/Shanghai")).isoformat(timespec="seconds")


def kind(config):
    kwargs = (config.get("agents") or [{}])[0].get("kwargs", {})
    if config.get("install_only"):
        return "安装检查（无模型）"
    if kwargs.get("smoke"):
        return "合成联调（无模型，非业务交付）"
    if kwargs.get("role_probe"):
        return "角色切换探针（真实模型，非业务交付）"
    return "文档 rollout（真实模型）"


def job_config(job):
    return read_json(job / "config.json") or read_json(job.parent.parent / ".prepared" / job.name / "job.json")


def trial_status(trial, config):
    state = read_json(trial / "workflow/state.json")
    result = read_json(trial / "result.json")
    if result.get("exception_info"):
        return "failed"
    if state:
        return state.get("status", "unknown")
    if config.get("install_only") and result.get("finished_at"):
        return "install-finished"
    return "incomplete"


def write_generated(path, text):
    if path.exists() and MARKER not in path.read_text():
        raise ValueError(f"Refusing to replace a manually authored report: {path}")
    path.write_text(MARKER + "\n\n" + text.rstrip() + "\n")


def write_report(job):
    job = Path(job).resolve()
    config = job_config(job)
    summary = read_json(job / "result.json")
    trials = sorted(p for p in job.iterdir() if p.is_dir() and
                    ((p / "config.json").exists() or (p / "result.json").exists() or (p / "workflow").exists()))
    lines = [f"# Rollout report：{job.name}", "", f"类型：{kind(config)}。",
             f"开始：{local_time(summary.get('started_at'))}；结束：{local_time(summary.get('finished_at'))}（上海时间）。",
             "", "本报告由运行器根据状态与文件证据生成；`review.md` 是 Agent 的技术自审报告，两者用途不同。",
             "本工作流关闭 Harbor verifier；Harbor 的 Mean / reward 不是本次文档质量或成功与否的判断。", ""]
    for p in (job / "config.json", job / "result.json"):
        if p.exists():
            lines.append("- " + link(p.name, p, job))
    if not trials:
        lines += ["", "未找到 trial 记录。运行可能尚未启动或在创建 trial 前中断；没有完成证据。"]
    for trial in trials:
        state = read_json(trial / "workflow/state.json")
        result = read_json(trial / "result.json")
        agent = result.get("agent_info", {})
        model = agent.get("model_info", {}).get("name") or (config.get("agents") or [{}])[0].get("model_name", "未记录")
        lines += ["", f"## {trial.name}", "", f"状态：**{trial_status(trial, config)}**；模型：`{model}`。"]
        if state.get("status") == "blocked":
            lines += ["所有已接受产物保留，技术自审有未决项，流程停在交付边界。blocked 不等于工具异常，也不等于业务批准。"]
        if state.get("principal_session"):
            lines += [f"主原生会话：`{state['principal_session']}`。"]
        if state.get("continued_from"):
            source = Path(state["continued_from"])
            lines += ["续跑来源：" + link(str(source.parent.parent.name), source / "state.json", job) + "。前序已接受阶段沿用原记录，不是本 job 重新生成。"]
        for rel in ("workflow/state.json", "workflow/events.jsonl", "agent/codex.txt", "agent/sessions", "agent/trajectory.json", "result.json", "exception.txt"):
            target = trial / rel
            if target.exists():
                lines.append("- " + link(rel, target, job))
        if result.get("exception_info"):
            # Exception details can contain request data; link the raw log, copy only the class.
            lines += ["", f"异常类型：`{result['exception_info'].get('exception_type', 'unknown')}`；详情见 trial result / exception 日志。"]
        stages = state.get("stages", [])
        if stages:
            lines += ["", "### 阶段记录", "", "| 阶段 | 角色 | 状态 | 提交次数 |", "| --- | --- | --- | --- |"]
            for stage in stages:
                lines.append(f"| {stage['id']} | {stage['role']} | {stage['status']} | {len(stage.get('attempts', []))} |")
            lines += ["", "同一阶段在接受前的补交不属于阶段回退。各次门禁结果以 state.json 为准。"]
            sessions = {a.get("session_id") for s in stages for a in s.get("attempts", []) if a.get("session_id")}
            lines += [f"记录到的主会话数：{len(sessions)}；模式：{state.get('mode', '未记录')}。"]
            first = next((s for s in stages if s.get("role") == "pm" and s.get("outputs", {}).get("prd.md")), None)
            inputs = [a.get("prd_input_sha256") for s in stages if s.get("role") == "architect" for a in s.get("attempts", [])]
            if first and inputs:
                exact = all(v == first["outputs"]["prd.md"] for v in inputs)
                lines += [f"PRD 输出 / 技术阶段输入哈希：{'一致' if exact else '不一致或缺失'}。"]
            lines += ["", "### 已接受产物", "", "以 workflow/accepted 为正式交付，artifacts 中可能含未接受草稿。", "",
                      "| 文件 | SHA256 | 当前文件校验 |", "| --- | --- | --- |"]
            for stage in stages:
                for name, expected in stage.get("outputs", {}).items():
                    target = trial / "workflow/accepted" / stage["id"] / name
                    matches = target.is_file() and hashlib.sha256(target.read_bytes()).hexdigest() == expected
                    lines.append(f"| {link(stage['id'] + '/' + name, target, job)} | `{expected}` | {'一致' if matches else '缺失或不一致'} |")
            for target in sorted((trial / "workflow/attempts").glob("*/*/*/native-evidence.json")):
                lines += ["", "原生角色证据：" + link(str(target.relative_to(trial / "workflow")), target, job)]
        if state.get("role_probe"):
            lines += ["", "### 原生角色探针", "", "| 角色 | 会话 | 回复 |", "| --- | --- | --- |"]
            for record in state.get("records", []):
                lines.append(f"| {record['role']} | `{record['session_id']}` | {record['response']} |")
        for target in sorted(trial.glob("artifacts/**/environment-check.json")):
            lines += ["", "环境检查：" + link("environment-check.json", target, job)]
        review = trial / "workflow/accepted/sprint1/tech-design/review.md"
        if review.exists():
            text = review.read_text()
            start = text.find("## 4. 问题与处置")
            end = text.find("## 5.", start)
            lines += ["", "### Agent 自审问题", "", "下表来自 " + link("review.md", review, job) + "，不代表独立审核。", ""]
            if start >= 0 and end > start:
                lines += [text[start:end].split("\n", 1)[1].strip()]
    lines += ["", "## 适用边界", "", "结构门禁、文件哈希和角色证据不证明业务设计正确。本阶段未执行 Saleor 功能开发、业务测试或部署。合成联调与角色探针不能作为真实 PRD/TDD 交付。"]
    write_generated(job / "report.md", "\n".join(lines))
    return job / "report.md"


def write_index(jobs):
    jobs = Path(jobs).resolve()
    lines = ["# Rollout 记录索引", "", "先读每个 job 的 report.md，再按链接查看状态、原生日志和已接受产物。历史失败记录保留。", "",
             "| Job / 报告 | 类型 | 状态 |", "| --- | --- | --- |"]
    for job in sorted(jobs.iterdir(), reverse=True):
        if not job.is_dir() or not (job / "report.md").exists():
            continue
        config = job_config(job)
        trials = [p for p in job.iterdir() if p.is_dir() and ((p / "result.json").exists() or (p / "workflow").exists())]
        statuses = ", ".join(sorted({trial_status(p, config) for p in trials})) or "incomplete"
        lines.append(f"| {link(job.name, job / 'report.md', jobs)} | {kind(config)} | {statuses} |")
    write_generated(jobs / "README.md", "\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("job", type=Path, nargs="?")
    parser.add_argument("--all", action="store_true", help="Backfill reports for local jobs; no Agent calls")
    args = parser.parse_args()
    if bool(args.job) == args.all:
        parser.error("Pass a job directory or --all")
    jobs = HERE / "jobs" if args.all else args.job.resolve().parent
    targets = sorted(p for p in jobs.iterdir() if p.is_dir() and (p / "config.json").exists()) if args.all else [args.job]
    for job in targets:
        print(write_report(job))
    write_index(jobs)


if __name__ == "__main__":
    main()
